version: '3.7'
services:
  php:
    image: php:latest
    env_file:
      - .env
    working_dir: /var/www/symfony
    volumes:
      - .:/var/www/symfony:delegated

  composer:
    image: composer:latest
    env_file:
      - .env
    working_dir: /var/www/symfony
    volumes:
      - .:/var/www/symfony:delegated
