---
# See some example to configure this file : https://github.com/jbouzekri/PhumborBundle/blob/master/Resources/doc/reference.md
jb_phumbor:
  server:
    url: '%env(APP_PHUMBOR_HOST)%'
    secret: '%env(APP_PHUMBOR_SECRET)%'
  transformations:
    default:
      resize:
        width: 360
        height: 500
